#!/usr/bin/env bash
# Bash script that will display information about subdomains.

function check_subdomain {
    dig "${2}"."$1" | grep -A1 'ANSWER SECTION:' | \
    awk 'FNR == 2 {printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$2"
}

domain_names=("www" "lb-01" "web-01" "web-02")

if [ $# -lt 1 ]
then
    echo "*** Provide domain name ***"
elif [ $# -eq 1 ]
then
    for i in "${domain_names[@]}";
    do
        check_subdomain "$1" "$i"
    done
else
    check_subdomain "$1" "$2"
fi

