#!/bin/bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) 
# using curl, it must return a page that contains the string Holberton School


apt-get update
apt-get install -y nginx
service nginx start
sed -i 's/\(listen\s*.*\)\(:[0-9]\+\)\?;/\180;/g' /etc/nginx/sites-available/default
service nginx restart
echo "<html><head><title>Hello World!</title></head><body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null
echo "Nginx installed and configured. Access http://your_server_ip/ to see Hello World!"
