#!/bin/bash
#script that accepts one argument
# script should run the whoami command under user passed as an argument

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

sudo -u "$1" whoami
